### ISSUE TITLE
Power does not reset after battle end

### ISSUE THREAD

**Issue by theCoosome** [EpicBlueCircles/Turn-based-battler#1]
After fighting coo33 vs siv, (coo33 won) fighting durik against alpha, alpha started with -3 power.

**Comment by theCoosome** [comment]
NO stats reset on winning and then fighting again, confirmed by playing as coosome again after winning, still boosted by plan ahead. (might be good if player can be locked to character after winning, unlocked after losing.)

**Comment by Jimgrind** [comment]
it's durric

Ben green
